{
 "title": "ForenWAF",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "PREDICTIONS",
    "query": {
     "query": "from(bucket: \"waf_predictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ai_analysis\")\r\n  |> filter(fn: (r) => r._field == \"summary\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ _value: r._value }))\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Attacks Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n  |> range(start: -30d) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"waf_stats\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")           \r\n  |> group()                                            \r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Attacks Last week",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n  |> range(start: -7d) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"waf_stats\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")           \r\n  |> group()                                            \r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Attacks Last 24H",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n  |> range(start: -24h) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"waf_stats\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")           \r\n  |> group()                                            \r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Attacks Last 1H",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n  |> range(start: -1h) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"waf_stats\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")           \r\n  |> group()                                            \r\n  |> sum()\r\n\r\n"
    }
   ]
  },
  { "title": "Forensics analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Analysis and Predictions",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "repeat": "PREDICTIONS",
   "options": {
    "content": "<div style=\"text-align:center;\">\n <h1> 🔍 Web Attack Analysis & Predictions (Last 24 hours)</h2>\n\n</div>\n\n  <h4>🛡️ ${PREDICTIONS} </h4>\n\n"
   }
  },
  { "title": "Logs Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top Attacks of all time",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 17, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n  |> range(start: -365d)  \r\n  |> filter(fn: (r) => r._measurement == \"waf_stats\") \r\n  |> filter(fn: (r) => r.type == \"attack_type\")\r\n  |> filter(fn: (r) => r.value != \"Unclassified\")\r\n  |> filter(fn: (r) => r.value != \"Scanner Detection\")\r\n  |> filter(fn: (r) => r.value != \"Brute Force\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> group(columns: [\"value\"])\r\n  |> sum()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> map(fn: (r) => ({\r\n      Attack_typeIs: r.value,  \r\n      CountOfAttacks: r._value  \r\n    }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"_field\", \"_measurement\", \"value\", \"type\"]) \r\n  |> yield(name: \"top_attacks\")"
    }
   ]
  },
  {
   "title": "Attack types by country",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 7, "x": 17, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"waf_countries\")\r\n  |> group(columns: [\"country\", \"attack_type\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with \"Attacks From\": r._value}))  \r\n  |> group(columns: [\"country\"])\r\n  |> top(n: 5, columns: [\"Attacks From\"])\r\n  |> sort(columns: [\"country\", \"Attacks From\"], desc: true)\r\n  |> drop(columns: [\"_value\"])\r\n  |> yield(name: \"attack_types_by_country\")"
    }
   ]
  },
  {
   "title": "Last Critical Attacks (24 H)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"waf_data\")\r\n|> range(start: -90d)\r\n|> filter(fn: (r) => r._measurement == \"waf_stats\")\r\n|> filter(fn: (r) => r._field == \"count\")\r\n|> filter(fn: (r) => r.severity != \"INFO\")\r\n|> filter(fn: (r) => r.type == \"attack_type\")\r\n|> filter(fn: (r) => r.value != \" \")\r\n|> map(fn: (r) => ({\r\n      r with \r\n      attack_label: r.severity + \" | \" + r.type + \" | Rule \" + r.value\r\n   }))\r\n|> group(columns: [\"attack_label\"])\r\n|> aggregateWindow(every: 5m, fn: count, createEmpty: false)\r\n|> yield(name: \"count\")\r\n"
    }
   ]
  }
 ]
}